#!/usr/bin/bash
export DISPLAY=:0

hdmi=$(xrandr -d :0 | grep "HDMI1" | cut -d" " -f2)

if [ "$hdmi" == "connected" ];
then
  xrandr -d :0 --output HDMI1 --auto --output eDP1 --off
  else
  xrandr --auto
fi
