#!/usr/bin/env bash
hdmi=($(xrandr --query | grep "HDMI1" | cut -d" " -f2))
if [ "$hdmi" == "connected" ];
then
	xrandr --output HDMI1 --auto --output eDP1 --off &
  else
	xrandr --output eDP1 --auto --output HDMI1 --off &
fi
