#!/bin/bash

[ -z "$1" ] && echo "Usage: $0 <image> <x> <y> <max height> <max width>" && exit
source "`ueberzug library`"

ImageLayer 0< <(
		ImageLayer::add [identifier]="example0" [x]="0" [y]="0" [max_width]="60" [max_height]="60" [path]="$1"
		while :
		do
		read
		done;
)
